version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g yarn@latest
      - >
        yarn global add
        typescript
        serverless serverless-webpack
        copy-webpack-plugin
        webpack webpack-node-externals
        ts-loader ts-node
        copyfiles rimraf
        turbo
  pre_build:
    commands:
      - printenv
      - echo `date +%s` > timestamp
      - echo Build started on `date`
      # - chmod +x ./bin/deploy/build-aws.sh
      - chmod +x ./bin/deploy/build-single-service.sh
  build:
    commands:
      # - npm cache verify
      # - npm install
      - ./bin/deploy/build-single-service.sh
