version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm cache verify
      - >
        npm install -g 
        serverless serverless-webpack serverless-offline serverless-plugin-typescript
        copy-webpack-plugin
        webpack webpack-node-externals
        copyfiles
        turbo
  pre_build:
    commands:
      - printenv
      - echo `date +%s` > timestamp
      - echo Build started on `date`
      - chmod +x ./bin/deploy/build-aws.sh
  build:
    commands:
      - npm cache verify
      #- npm install
      - ./bin/deploy/build-aws.sh
