version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: TezkoGeslo123