# console: true
# org: apillonadmin
# app: apillon-v2
service: at-v2-mailing-service-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      modeModulesRelativeDir: '../../'
      forceExclude:
        - aws-sdk
    packagerOptions:
      lockFile: '../../package-lock.json'
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*'

plugins:
  - serverless-webpack
  # - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor

  environment: ${file(../../bin/deploy/env/env.yml)}
  #   ACCESS_FUNCTION_NAME: 'at-v2-access-service-${self:provider.stage}'
  #   MONITORING_FUNCTION_NAME: 'at-v2-mailing-service-${self:provider.stage}'

# you can add packaging information here
package:
  patterns:
    - '!dist/**'
  excludeDevDependencies: true

functions:
  mailing-service:
    handler: ./src/handler.handler
    name: 'at-v2-mailing-service-${self:provider.stage}'
    description: AT Logging & mailing & Alerting Service
    memorySize: 512
    timeout: 30
