# console: true
# org: apillonadmin
# app: apillon-v2
service: apillon-storage-service-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'npm'
    includeModules: true
    packagerOptions:
      lockFile: '../../package-lock.json'
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor
  vpc:
    securityGroupIds:
      - sg-091bc1ce7424a7921
    subnetIds:
      - subnet-0bea6dd0c2a5ecc61
      - subnet-085447b898128fc92
      - subnet-0ed148d48e931f5fa

  environment: ${file(../../bin/deploy/env/env.yml)}

package:
  individually: true
  patterns:
    - '!dist/**'
  excludeDevDependencies: true

functions:
  storage-service:
    handler: ./src/handler.handler
    name: 'apillon-storage-service-${self:provider.stage}'
    description: Apillon storage Service
    memorySize: 512
    timeout: 90
  storage-service-worker:
    handler: ./src/workers/worker-executor.handler
    name: apillon-storage-service-worker-${self:provider.stage}
    description: Serverless workers for Apillon storage microservice
    memorySize: 512
    timeout: 900
    reservedConcurrency: 30
    environment:
      AWS_WORKER_LAMBDA_NAME: ${self:functions.storage-service-worker.name}
    events:
      - schedule: cron(${env:CRON_SCHEDULE, '0/1 * * * ? *'})
      - sqs:
          arn: ${env:WORKER_SQS_ARN} #arn:aws:sqs:eu-west-1:018021943180:apillon-storage-queue-dev
          batchSize: 4
          maximumBatchingWindow: 5
          functionResponseType: ReportBatchItemFailures
  storage-service-builder:
    handler: ./src/workers/builder-executor.handler
    name: apillon-storage-service-builder-${self:provider.stage}
    description: Worker for building projects on Apillon
    memorySize: 512
    timeout: 900
    reservedConcurrency: 10
    ephemeralStorageSize: 3072
    environment:
      APILLON_API_URL: ${env:BUILDER_APILLON_API_URL}
      AWS_WORKER_LAMBDA_NAME: ${self:functions.storage-service-builder.name}
      PATH: '/var/lang/bin:/opt/bin:/opt/node_modules/.bin:/bin:/usr/bin:/opt/apillon_cli/bin:/opt/apillon_cli/node_modules/.bin:/var/lang/bin:${PATH}'
    events:
      - sqs:
          arn: ${env:BUILDER_SQS_ARN}
          batchSize: 4
          maximumBatchingWindow: 5
          functionResponseType: ReportBatchItemFailures
    layers:
      - arn:aws:lambda:eu-west-1:018021943180:layer:git-layer:3
