# console: true
# org: apillonadmin
# app: apillon-v2
service: apillon-storage-service-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      modeModulesRelativeDir: '../../'
      forceExclude:
        - aws-sdk
    packagerOptions:
      lockFile: '../../package-lock.json'
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*'

plugins:
  - serverless-webpack
  # - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor

  environment:
    ${file(../../bin/deploy/env/env.yml)}
    # ACCESS_FUNCTION_NAME: 'apillon-storage-service-${self:provider.stage}'
    # MONITORING_FUNCTION_NAME: 'apillon-monitoring-service-${self:provider.stage}'

# you can add packaging information here
package:
  patterns:
    - '!dist/**'
  excludeDevDependencies: true

functions:
  storage-service:
    handler: ./src/handler.handler
    name: 'apillon-storage-service-${self:provider.stage}'
    description: Apillon storage Service
    memorySize: 512
    timeout: 30
  storage-service-worker:
    handler: ./src/workers/worker-executor.handler
    name: storage-service-worker-${self:provider.stage}
    description: Serverless workers for Apillon storage microservice
    memorySize: 512
    timeout: 900
    reservedConcurrency: 30
    environment:
      AWS_WORKER_LAMBDA_NAME: ${self:functions.storage-service-worker.name}
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:018021943180:storage-service-queue-dev #${env:WORKER_SQS_ARN}
          batchSize: 4
          maximumBatchingWindow: 5
