# console: true
# org: apillonadmin
# app: apillon-v2
service: apillon-dev-console-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    packager: "npm"
    includeModules:
      forceInclude:
        - '@nestjs/core'
        - '@nestjs/common'
        - '@nestjs/platform-express'
    packagerOptions:
      lockFile: '../../package-lock.json'
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*|**/test/**/|**/*\.spec\.ts|**/*\.spec\.js'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  vpc:
    securityGroupIds:
      - sg-091bc1ce7424a7921
    subnetIds:
      - subnet-0bea6dd0c2a5ecc61
      - subnet-085447b898128fc92
      - subnet-0ed148d48e931f5fa

  environment:
    ${file(../../bin/deploy/env/env.yml)}

package:
  individually: true
  patterns:
    - '!dist/**'
  excludeDevDependencies: true

functions:
  dev-console-api:
    handler: ./src/lambda.handler
    name: 'apillon-dev-console-api-${self:provider.stage}'
    description: API for Apillon developer console
    memorySize: 512
    timeout: 30
    events:
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
