# console: true
# org: apillonadmin
# app: apillon-v2
service: apillon-api-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      modeModulesRelativeDir: '../../'
      forceExclude:
        - aws-sdk
    packagerOptions:
      lockFile: '../../package-lock.json'
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*'

plugins:
  - serverless-webpack
  # - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  vpc:
    securityGroupIds:
      - sg-091bc1ce7424a7921
    subnetIds:
      - subnet-0bea6dd0c2a5ecc61
      - subnet-085447b898128fc92
      - subnet-0ed148d48e931f5fa

  environment:
    ${file(../../bin/deploy/env.yml)}
    # ACCESS_FUNCTION_NAME: 'apillon-access-service-${self:provider.stage}'
    # MONITORING_FUNCTION_NAME: 'apillon-monitoring-service-${self:provider.stage}'

# you can add packaging information here
package:
  patterns:
    - '!dist/**'
    # - '!**/*.*'
    # - '!.turbo'
    # - './dist/**'
  excludeDevDependencies: true

functions:
  authentication-service:
    handler: ./src/handler.handler
    name: 'apillon-authentication-service-${self:provider.stage}'
    description: Apillon Authorization Service
    memorySize: 512
    timeout: 30
  authentication-service-worker:
    handler: ./src/workers/worker-executor.handler
    name: apillon-authentication-service-worker-${self:provider.stage}
    description: Serverless workers for Apillon authentication service
    memorySize: 512
    timeout: 900
    reservedConcurrency: 30
    environment:
      AWS_WORKER_LAMBDA_NAME: ${self:functions.authentication-service-worker.name}
    events:
      - sqs:
          arn: ${env:WORKER_SQS_ARN} #arn:aws:sqs:eu-west-1:018021943180/apillon-authentication-queue-dev
          batchSize: 4
          maximumBatchingWindow: 5
