# console: true
# org: authtrailadmin
# app: authtrail-v2
service: at-v2-monitoring-service-${opt:stage, 'dev'}
frameworkVersion: '3'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    excludeFiles: '**/*\.test\.js|**/*\.test\.ts|**/tests/**/*'
  serverless-offline:
    httpPort: 6201
    lambdaPort: 6202

plugins:
  # - serverless-webpack
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  iam:
    role: arn:aws:iam::018021943180:role/serverless-workers-executor

  environment: ${file(../../bin/deploy/env/env.yml)}
  #   AT_AMS_FUNCTION_NAME: 'at-v2-access-service-${self:provider.stage}'
  #   AT_LMAS_FUNCTION_NAME: 'at-v2-monitoring-service-${self:provider.stage}'

# you can add packaging information here
package:
  patterns:
    - '!dist/**'
  excludeDevDependencies: true

functions:
  monitoring-service:
    handler: ./src/handler.handler
    name: 'at-v2-monitoring-service-${self:provider.stage}'
    description: AT Logging & Monitoring & Alerting Service
    memorySize: 512
    timeout: 30
